#!/usr/bin/env bash
# check_commit_message.sh - Validate a single commit message
# Usage: check_commit_message.sh <message-file>

set -euo pipefail

if [ $# -lt 1 ]; then
    echo "Usage: $0 <commit-message-file>" >&2
    exit 1
fi

MSG_FILE="$1"
MSG=$(cat "$MSG_FILE")

# Check for forbidden trailers
if echo "$MSG" | grep -qiE "^Co-Authored-By:|^Co-authored-by:|^Pair-Programmed-By:|Generated by|Generated with"; then
    echo "ERROR: Forbidden trailer or AI signature detected in commit message." >&2
    echo "Remove Co-Authored-By, Pair-Programmed-By, or AI tool signatures." >&2
    exit 1
fi

# Check conventional commits format (first line only)
FIRST_LINE=$(echo "$MSG" | head -1)
VALID_TYPES="feat|fix|docs|refactor|test|chore|build|ci|perf|revert|style"

if ! echo "$FIRST_LINE" | grep -qE "^(${VALID_TYPES})(\([^)]+\))?: .+"; then
    echo "ERROR: Commit message does not follow Conventional Commits format." >&2
    echo "Expected: <type>(<scope>): <description>" >&2
    echo "Allowed types: ${VALID_TYPES}" >&2
    echo "Got: ${FIRST_LINE}" >&2
    exit 1
fi

exit 0
